### PR TITLE
add paper theme

### PR DESCRIPTION
**Pull request by ckouder**
Screenshot of my A11y card:
Screen Shot 2019-10-29 at 4 10 37 PM

For assistance: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

### CODE REVIEW

**Comment by ckouder** [comment]
#12

**Comment by TerabyteTiger** [comment]
Hi! 

This is a great start, but currently the header doesn't have enough contrast between the text and background color. 

If you could update that and ping me in a comment here once updated, I can approve the PR and merge it in 😄

**Comment by ckouder** [comment]
Do you mean the text color is too similar to the link color? @12vanblart

**Comment by TerabyteTiger** [comment]
The contrast between the Header text color and the Header background color is too low, so users may have a hard time being able to read the words. 

You can find more about contrast here: https://webaim.org/resources/contrastchecker/

**Pull request closed without merging**
