### PR TITLE
Violet-theme

### PR DESCRIPTION
**Pull request by PedroMantovani**
add a violet theme

Screenshot of my card:
Capturar

For assistance: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

### CODE REVIEW

**Comment by PedroMantovani** [comment]
My violet theme

**Comment by TerabyteTiger** [comment]
Hi! This is a great start, but currently doesn't pass the WCAG requirements to be accessible. 

If you could adjust the colors so that the A11y card displays "AA" or "AAA" compliant we can merge it in. 

_As an additional note: It looks like you added a `-` in your username, which is causing the image to not render._

**Comment by PedroMantovani** [comment]
Sorry about that, i'm sending again a new color theme, if can you see, I appreciate it.

**Comment by TerabyteTiger** [comment]
Looking much better! 

Thanks for the addition 😄

**Pull request merged**
