### PR TITLE
Add primarily pink theme

### PR DESCRIPTION
**Pull request by karaluton**
Screenshot of my A11y card:
 
Screen Shot 2019-10-06 at 5 06 49 PM

For assistance: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

### CODE REVIEW

**Comment by TerabyteTiger** [comment]
Thanks for the contribution!

If you could follow the top answer here to remove `package-lock.json` from the PR I can merge it in: 
https://stackoverflow.com/questions/39459467/remove-a-modified-file-from-pull-request

**Comment by TerabyteTiger** [comment]
Actually - Could you run `npm --version` and let me know what version is returned? 

The changes to `package-lock.json` might be valid 😅

**Comment by karaluton** [comment]
Hey! It's 6.4.1.

**Comment by TerabyteTiger** [comment]
Ok, I was able to update package-lock so that I won't keep having that issue pop up 😄

Thanks for your help and submitting an awesome theme 💕!

**Pull request merged**
